//
//  EngineLine.swift
//  Holyoke (macOS)
//
//  Created by Brian Yu on 6/22/22.
//

import Foundation

/**
 Represents a line from engine analysis.
 */
struct Line {
    /**
     The number of half-moves deep the engine has explored.
     */
    let depth: Int
    
    /**
     The centipawn value of the line.
     Positive values are better for White,
     Negative values are better for Black.
     */
    let cp: Double
    
    /**
     The move generated by the engine.
     */
    let move: Move
    
    /**
     SAN notation of the variation generated by the engine.
     */
    let variation: String
}
